FROM osrf/ros:kinetic-desktop-full
RUN apt-get update &&\
    apt-get install -y \
        libgl1-mesa-glx \
        libgl1-mesa-dri \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
ADD wait-for-it.sh /
CMD /wait-for-it.sh -s -q -t 0 master:11311 -- \
    rqt_image_view /aux_camera/image_raw
