version: '2.3'
networks:
  robot:
    enable_ipv6: true
    ipam:
      config:
        - subnet: fdff:0cea::/32
  gigecamera:
    driver: macvlan
    ipam:
      config:
        - subnet: 192.168.0.0/16
          ip_range: 192.168.2.128/26
    driver_opts:
      parent: enp0s25

volumes:
  calibration:

services:
  master:
    image: ros:kinetic-ros-core
    environment:
      - ROS_MASTER_URI=http://master:11311
      - ROS_HOSTNAME=master
    command: roslaunch --core
    networks:
      - robot
    stop_signal: SIGINT
  vimba_camera:
    depends_on:
      - master
    build:
      context: .
      dockerfile: Dockerfile.vimba
    image: vimba
    environment:
      - ROS_MASTER_URI=http://master:11311
      - ROS_HOSTNAME=vimba_camera
    networks:
      robot:
      gigecamera:
        ipv4_address: 192.168.1.1
    volumes:
      - type: volume
        source: calibration
        target: /calibration
        read_only: false
      - type: bind
        source: /home/russel/vimba-camera/camera.launch
        target: /camera.launch
    stop_signal: SIGINT
  ptgrey_camera:
    depends_on:
      - master
    build:
      context: .
      dockerfile: Dockerfile.flycap
    image: flycap
    environment:
      - ROS_MASTER_URI=http://master:11311
      - ROS_HOSTNAME=ptgrey_camera
    networks:
      robot:
      gigecamera:
          ipv4_address: 192.168.5.1
    volumes:
      - type: volume
        source: calibration
        target: /calibration
        read_only: false
      - type: bind
        source: /home/russel/vimba-camera/ptgrey.launch
        target: /camera.launch
    stop_signal: SIGINT
  viewer:
    depends_on:
      - master
    build:
      context: .
      dockerfile: Dockerfile.viewer
    image: osrf_ros:kinetic-desktop-opengl
    environment:
      - ROS_MASTER_URI=http://master:11311
      - ROS_HOSTNAME=viewer
      - DISPLAY=:0.0
      - QT_X11_NO_MITSHM=1
    networks:
      - robot
    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
        read_only: false
    devices:
      - "/dev/dri:/dev/dri"
    stop_signal: SIGINT
